// Code generated by protoc-gen-ext. DO NOT EDIT.
// source: github.com/solo-io/gloo-mesh/api/networking/v1/ratelimit/rate_limit.proto

package ratelimit

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"strings"

	"github.com/golang/protobuf/proto"
	equality "github.com/solo-io/protoc-gen-ext/pkg/equality"
)

// ensure the imports are used
var (
	_ = errors.New("")
	_ = fmt.Print
	_ = binary.LittleEndian
	_ = bytes.Compare
	_ = strings.Compare
	_ = equality.Equalizer(nil)
	_ = proto.Message(nil)
)

// Equal function
func (m *GatewayRateLimit) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*GatewayRateLimit)
	if !ok {
		that2, ok := that.(GatewayRateLimit)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	if h, ok := interface{}(m.GetRatelimitServerRef()).(equality.Equalizer); ok {
		if !h.Equal(target.GetRatelimitServerRef()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetRatelimitServerRef(), target.GetRatelimitServerRef()) {
			return false
		}
	}

	if h, ok := interface{}(m.GetRequestTimeout()).(equality.Equalizer); ok {
		if !h.Equal(target.GetRequestTimeout()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetRequestTimeout(), target.GetRequestTimeout()) {
			return false
		}
	}

	if m.GetDenyOnFail() != target.GetDenyOnFail() {
		return false
	}

	return true
}

// Equal function
func (m *RateLimitClient) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*RateLimitClient)
	if !ok {
		that2, ok := that.(RateLimitClient)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	switch m.ConfigType.(type) {

	case *RateLimitClient_Raw:
		if _, ok := target.ConfigType.(*RateLimitClient_Raw); !ok {
			return false
		}

		if h, ok := interface{}(m.GetRaw()).(equality.Equalizer); ok {
			if !h.Equal(target.GetRaw()) {
				return false
			}
		} else {
			if !proto.Equal(m.GetRaw(), target.GetRaw()) {
				return false
			}
		}

	default:
		// m is nil but target is not nil
		if m.ConfigType != target.ConfigType {
			return false
		}
	}

	return true
}

// Equal function
func (m *RawRateLimit) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*RawRateLimit)
	if !ok {
		that2, ok := that.(RawRateLimit)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	if len(m.GetRateLimits()) != len(target.GetRateLimits()) {
		return false
	}
	for idx, v := range m.GetRateLimits() {

		if h, ok := interface{}(v).(equality.Equalizer); ok {
			if !h.Equal(target.GetRateLimits()[idx]) {
				return false
			}
		} else {
			if !proto.Equal(v, target.GetRateLimits()[idx]) {
				return false
			}
		}

	}

	return true
}

// Equal function
func (m *RouteRateLimit) Equal(that interface{}) bool {
	if that == nil {
		return m == nil
	}

	target, ok := that.(*RouteRateLimit)
	if !ok {
		that2, ok := that.(RouteRateLimit)
		if ok {
			target = &that2
		} else {
			return false
		}
	}
	if target == nil {
		return m == nil
	} else if m == nil {
		return false
	}

	if h, ok := interface{}(m.GetRatelimitServerConfigSelector()).(equality.Equalizer); ok {
		if !h.Equal(target.GetRatelimitServerConfigSelector()) {
			return false
		}
	} else {
		if !proto.Equal(m.GetRatelimitServerConfigSelector(), target.GetRatelimitServerConfigSelector()) {
			return false
		}
	}

	switch m.RateLimitConfigType.(type) {

	case *RouteRateLimit_Raw:
		if _, ok := target.RateLimitConfigType.(*RouteRateLimit_Raw); !ok {
			return false
		}

		if h, ok := interface{}(m.GetRaw()).(equality.Equalizer); ok {
			if !h.Equal(target.GetRaw()) {
				return false
			}
		} else {
			if !proto.Equal(m.GetRaw(), target.GetRaw()) {
				return false
			}
		}

	case *RouteRateLimit_RatelimitClientConfigRef:
		if _, ok := target.RateLimitConfigType.(*RouteRateLimit_RatelimitClientConfigRef); !ok {
			return false
		}

		if h, ok := interface{}(m.GetRatelimitClientConfigRef()).(equality.Equalizer); ok {
			if !h.Equal(target.GetRatelimitClientConfigRef()) {
				return false
			}
		} else {
			if !proto.Equal(m.GetRatelimitClientConfigRef(), target.GetRatelimitClientConfigRef()) {
				return false
			}
		}

	default:
		// m is nil but target is not nil
		if m.RateLimitConfigType != target.RateLimitConfigType {
			return false
		}
	}

	return true
}
